### PR TITLE
Add dist to .gitignore

### PR DESCRIPTION
**Pull request by quinn-dev**

### CODE REVIEW

**Comment by andrew-sayers** [comment]
This seems like a fine change, but will need a couple of fixes before it can be accepted:

1. This particular commit wouldn't have merged into the `built` branch, because the preceding `/docs` line wasn't present in that branch.  I've now fixed that with [a commit to the main branch](https://github.com/sleepdiary/dashboard/commit/fc88bf48dad087a7afc7c462d3dd30b099063fbd) and [a sequence of commits to the `built` branch](https://github.com/sleepdiary/dashboard/commits/built), but you'll need to resolve a trivial conflict before resubmitting
2. The justification for this change isn't immediately clear - as I hinted above, the `built` branch saves to `/docs` (so GitHub Pages will look at it), and ordinary users shouldn't need to build the site at all, so this directory should never actually exist in the real world.  To put it another way, imagine someone else came along wanting to delete this unnecessary line.  I'd be in a similar situation to [this previous pull request](https://github.com/sleepdiary/dashboard/pull/3), where I couldn't think of a reason to keep it but also suspected that reason might exist.  Could you add a line or two to the commit message, justifying this change?

(I'm closing this because, to the best of my knowledge, the only way to submit an updated PR is to open a new one)

**Comment by quinn-dev** [comment]
Any additional commits I push to the feature branch `quinn-dev:add-dist-to-gitignore` will automatically appear in this PR, so there isn't a need to close it.

I can see how a bit more justification could clear things up, though I thought that the change and the intention behind it were fairly obvious.

The intention behind this PR is for `git` to ignore any files in the `dist/` folder and prevent them from being commited accidentally. This might not be relevant when using Docker during development, but it is relevant when using a `npm` / `yarn` workflow.

I'm not quite sure how exactly you are using the `built` branch, so I'd appreciate it if you could elaborate on that.

**Comment by andrew-sayers** [comment]
Ah, so for example if you did e.g. `yarn build` in the wrong directory, it would protect against that.  That makes sense, so you just need to `git commit --amend` that line into this commit.

I'll be interested to see how GitHub handles it, but I had assumed this PR would complain if you were to edit a commit and/or `git rebase` the commit onto the latest master branch.

**Comment by andrew-sayers** [comment]
Reopening so we don't forget about this one.

**Comment by andrew-sayers** [comment]
Closing this in favour of the above issue - any further discussion can go there for now.

**Pull request closed without merging**
